ROUNDCUBE_PROVISION_CONFIG='/var/www/roundcubemail/config/config.inc.php.provision'
RANDOM_KEY=$(openssl rand -base64 24)

cat << EOF >> ${ROUNDCUBE_PROVISION_CONFIG}
<?php
// AUTOGENERATED CONFIG FILE
\$config['des_key']          = "${RANDOM_KEY}";
\$config['log_driver']       = "syslog";
\$config['force_https']      = false;
\$config['use_https']        = false;
\$config['password_charset'] = "UTF-8";
\$config['default_charset']  = "UTF-8";

\$config['plugins'] = array(
	'managesieve',
	'zipdownload',
	'html5_notifier',
	'serverinfo',
	'thunderbird_labels'
);

EOF
