#!/usr/bin/bash
#
# Put customizations to your image in this file.

ROUNDCUBE_VERSION=1.0.1
PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Exit if any commands fail
set -o errexit

# Ensure we have updated standard packages
echo "* Updating standard packages.";
pkg_delete -v nodejs smtools
pkg_add -v nodejs smtools dtracetools htop
npm install smartdc -g
npm install jsontool -g

# Configuring image specific packages
echo "* Configuring image specific packages.";
mkdir /var/www/roundcubemail

# Download Roundcube and extract it to /var/www
echo "* Download and extract roundcube to /var/www"
curl -L "https://github.com/roundcube/roundcubemail/releases/download/${ROUNDCUBE_VERSION}/roundcubemail-${ROUNDCUBE_VERSION}.tar.gz" | tar xz -C /var/www/roundcubemail --strip-components=1

# Setup permissions for roundcubemail folders
echo "* Setup permissions for roundcubemail folders"
chown -R www:www /var/www

# Nginx SSL folder
echo "* Create ssl folder"
mkdir -p /opt/local/etc/nginx/ssl

echo "* Enable mdata-setup script"
svccfg import /tmp/mdata-setup.xml
rm /tmp/mdata-setup.xml

# Remove install folder from roundcube
echo "* Remove install folder from roundcube"
rm -r /var/www/roundcubemail/installer

# Clean up
echo "* Cleaning up."
rm -rf /root/*

# Prepare image for provisioning
sm-prepare-image -y
